included:
  - Source
  - Tests
  - ../GlobalPayments-iOS-SDK

disabled_rules:
  - force_cast
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - identifier_name
  - cyclomatic_complexity
  - nesting
  - type_name
  - inclusive_language

identifier_name:
  excluded:
    - id