import Foundation

public enum AlternativePaymentMethodType {
    case ASTROPAY_DIRECT
    case AURA
    case BALOTO_CASH
    case BANAMEX
    case BANCA_AV_VILLAS
    case BANCA_CAJA_SOCIAL
    case BANCO_GNB_SUDAMERIS
    case BANCO_CONSORCIO
    case BANCO_COOPERATIVO_COOPCENTRAL
    case BANCO_CORPBANCA
    case BANCO_DE_BOGOTA
    case BANCO_DE_CHILE_EDWARDS_CITI
    case BANCO_DE_CHILE_CASH
    case BANCO_DE_OCCIDENTE
    case BANCO_DE_OCCIDENTE_CASH
    case BANCO_DO_BRASIL
    case BANCO_FALABELLA_Chile
    case BANCO_FALABELLA_Columbia
    case BANCO_INTERNATIONAL
    case BANCO_PICHINCHA
    case BANCO_POPULAR
    case BANCO_PROCREDIT
    case BANCO_RIPLEY
    case BANCO_SANTANDER
    case BANCO_SANTANDER_BANEFE
    case BANCO_SECURITY
    case BANCOBICE
    case BANCOESTADO
    case BANCOLOMBIA
    case BANCOMER
    case BANCONTACT_MR_CASH
    case BANCOOMEVA
    case BANK_ISLAM
    case BANK_TRANSFER
    case BBVA_Chile
    case BBVA_Columbia
    case BCI_TBANC
    case BITPAY
    case BOLETO_BANCARIO
    case BRADESCO
    case CABAL
    case CARTAO_MERCADOLIVRE
    case CARULLA
    case CENCOSUD
    case CHINA_UNION_PAY
    case CIMB_CLICKS
    case CITIBANK
    case CMR
    case COLPATRIA
    case COOPEUCH
    case CORPBANCA
    case DANSKE_BANK
    case DAVIVIENDA
    case DRAGONPAY
    case EASYPAY
    case EFECTY
    case ELO
    case EMPRESA_DE_ENERGIA_DEL_QUINDIO
    case ENETS
    case ENTERCASH
    case E_PAY_PETRONAS
    case EPS
    case ESTONIAN_ONLINE_BANK_TRANSFER
    case FINLAND_ONLINE_BANK_TRANSFER
    case GIROPAY
    case HANDELSBANKEN
    case HELM_BANK
    case HIPERCARD
    case HONG_LEONG_BANK
    case IDEAL
    case INDONESIA_ATM
    case INSTANT_TRANSFER
    case INTERNATIONAL_PAY_OUT
    case ITAU_BRAZIL
    case ITAU_CHILE
    case O
    case LINK
    case LITHUANIAN_ONLINE_BANK_TRANSFER
    case MAGNA
    case MAXIMA
    case MAYBANK2U
    case MULTIBANCO
    case MYBANK
    case MYCLEAR_FPX
    case NARANJA
    case NARVESEN_LIETUVOS_SPAUDA
    case NATIVA
    case NORDEA
    case OSUUSPANKKI
    case OXXO
    case PAGO_FACIL
    case PAYPOST_LIETUVOS_PASTAS
    case PAYSAFECARD
    case PAYSBUY_CASH
    case PAYSERA
    case PAYU
    case PERLAS
    case POLI
    case POLISH_PAYOUT
    case POP_PANKKI
    case POSTFINANCE
    case PRESTO
    case PROVINCIA_NET
    case PRZELEWY24
    case PSE
    case QIWI
    case QIWI_PAYOUT
    case RAPI_PAGO
    case REDPAGOS
    case RHB_BANK
    case SAASTOPANKKI
    case SAFETYPAY
    case SANTANDER_BRAZIL
    case SANTANDER_MEXICO
    case SANTANDER_RIO
    case SCOTIABANK
    case SEPA_DIRECTDEBIT_MERCHANT_MANDATE_MODEL_C
    case SEPA_DIRECTDEBIT_PPPRO_MANDATE_MODEL_A
    case SEPA_PAYOUT
    case SERVIPAG
    case SINGPOST
    case SKRILL
    case SOFORTUBERWEISUNG
    case SOFORT
    case S_PANKKI
    case SURTIMAX
    case TARJETA_SHOPPING
    case TELEINGRESO
    case TESTPAY
    case TRUSTLY
    case TRUSTPAY
    case WEBMONEY
    case WEBPAY
    case WECHAT_PAY
    case ZIMPLER
    case UK_DIRECT_DEBIT
}
