import Foundation

public class Installment: NSObject, InstallmentEntity {
    
    /// <summary>
    /// Represents the account name
    /// </summary>
    public var AccountName: String?
    
    /// <summary>
    /// Represents the transaction was processed in a face to face(CP) scenario or a Customer Not Present (CNP) scenario.
    /// </summary>
    public var Channel: String?
    
    /// <summary>
    /// The amount to transfer between Payer and Merchant.
    /// It is always represented in the lowest denomination of the related currency. and with no decimal point.
    /// </summary>
    public var Amount: Double?
    
    /// <summary>
    /// Represents the currency of the amount.
    /// </summary>
    public var Currency: String?
    
    /// <summary>
    /// Represents the countty the merchant is domiciled in.
    /// </summary>
    public var Country: String?
    
    /// <summary>
    /// Represents the Merchant defined field to reference the transaction.
    /// </summary>
    public var Reference: String?
    
    /// <summary>
    /// This field indicates the installment program the merchant is participating in.
    /// </summary>
    public var Program: String?
    
    /// <summary>
    /// Represents unique identifier that is used to identify and reference an instance of this resource.
    /// This id is used when actioning or referencing a specific installment request.
    /// Begins with the three letters, INS.
    /// </summary>
    public var Id: String?
    
    /// <summary>
    /// Represents Global Payments time indicating when the object was created in ISO-8601 format.
    /// </summary>
    public var TimeCreated: Date?
    
    /// <summary>
    /// The type of installment request.
    /// </summary>
    public var `Type`: String?
    
    /// <summary>
    /// Indicates the status of the installment.
    /// </summary>
    public var Status: String?
    
    /// <summary>
    /// Represents a unique identifier that is used to identify and reference an instance of this resource.
    /// This id is used when actioning or referencing a specific merchant.
    /// Begins with the three letters, MER.
    /// </summary>
    public var MerchantId: String?
    
    /// <summary>
    /// Represents the merchant name.
    /// </summary>
    public var MerchantName: String?
    
    /// <summary>
    /// Represents the account id.
    /// </summary>
    public var AccountId: String?
    
    /// <summary>
    /// Represents unique identifier that is used to identify and reference an instance of this resource.
    /// This id is used when actioning or referencing a specific account.
    /// Begins with the three letters, TRA.
    /// </summary>
    public var terms: [Terms]?
    
    /// <summary>
    /// Represents the Action Result returned by GP API
    /// </summary>
    public var Action: Action?
    
    /// <summary>
    /// Represents the result code associated with the payment method used to process this transaction.
    /// </summary>
    public var Result: String?
    
    /// <summary>
    /// Represents the result message that better explains the result code.
    /// </summary>
    public var Message: String?
    
    /// <summary>
    /// Indicates how the payment method information was obtained by the Merchant for this transaction.
    /// </summary>
    public var EntryMode: String?
    
    /// <summary>
    /// Represents the Card Details
    /// </summary>
    public var Card: Card?
    
    /// <summary>
    /// Represents the Card Details
    /// </summary>
    public var CardDetails: CreditCardData?
    
    /// <summary>
    /// Indicates Code generated by the card provider when the card is successfully authorized.
    /// </summary>
    public var AuthCode: String?
    
    /// <summary>
    /// Represents the Encryption Details
    /// </summary>
    public var encryption: Encryption?
    
    /// <summary>
    /// Creates an installment
    /// </summary>
    /// <returns>Installment</returns>
    public func create(completion: ((Installment?, Error?) -> Void)?) {
        return create(configName: "default", completion: completion)
    }
    
    /// <summary>
    /// Creates an installment with configName
    /// </summary>
    /// <param name="configName"></param>
    /// <returns>Installment</returns>
    ///
    
    public func create(configName: String, completion: ((Installment?, Error?) -> Void)?) {
        InstallmentService.create(entity: self, configName: configName, completion: completion)
    }
}
