# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ios-3ds-sdk/Specs.git'

target 'Merchant3DS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Merchant3DS
  pod 'ThreeDS_SDK'
  pod 'GirdersSwift', '0.4.5'

  target 'Merchant3DSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Merchant3DSUITests' do
    # Pods for testing
  end

end

post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name.include? 'Coverage'
        config.build_settings['ENABLE_TESTABILITY'] = 'YES'
      end
    end
  end
end
