import Foundation

/// <summary>
/// Represents the action result return by GP API
/// </summary>
public class Action {
    /// <summary>
    /// Reprensents a unique identifier generated by Global Payments to identify an action.
    /// </summary>
    public var Id: String?
    /// <summary>
    /// Indicates the specific action taken.
    /// </summary>
    public var `Type`: String?
    /// <summary>
    /// Represents Global Payments time indicating when the object was created in ISO-8601 format.
    /// </summary>
    public var TimeCreated: String?
    /// <summary>
    /// Represents the result of the action executed.
    /// </summary>
    public var ResultCode: String?
    /// <summary>
    /// Represents id of the app that was used to create the token.
    /// </summary>
    public var AppId: String?
    /// <summary>
    /// Represents the name of the app the user gave to the application.
    /// </summary>
    public var AppName: String?
}
