import Foundation

public class PayLinkResponse: NSObject {
    /// A unique identifier generated by Global Payments to identify the link.
    public var id: String?
    /// A meaningful label for the merchant account set by Global Payments.
    public var accountName: String?
    /// The URL that the customer should be redirected to in order to make their payment.
    public var url: String?
    /// Indicates where a link is in its lifecycle.
    public var status: PayLinkStatus?
    /// Describes the type of link that will be created.
    public var type: PayLinkType?
    /// Indicates whether the link can be used once or multiple times
    public var usageMode: PaymentMethodUsageMode?
    /// The number of the times that the link can be used or paid.
    public var usageLimit: Int?
    /// Merchant defined field to reference the transaction.
    public var reference: String?
    /// A descriptive name for the link. This will be visible to the customer on the payment page.
    public var name: String?
    /// A detailed description of your link that will be visible to the customer on the payment page.
    public var descriptionPayLink: String?
    /// Indicates if you want to capture the customers shipping information on the hosted payment page.
    /// If you enable this field you can also set an optional shipping fee in the shipping_amount.
    public var isShippable: Bool?
    /// The number of times a link has been viewed.
    public var viewedCount: String?
    /// Indicates the date and time after which the link can no longer be used or paid.
    public var expirationDate: Date?
    /// Images that will be displayed to the customer on the payment page.
    public var images: [String]?
    
    public var allowedPaymentMethods: [PaymentMethodName]?
}
